# Generated by Django 5.2.6 on 2025-09-30 01:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.PositiveIntegerField(help_text='Número de rounds da sessão')),
                ('breaths_per_round', models.PositiveIntegerField(default=30, help_text='Respirações por round')),
                ('breath_duration', models.FloatField(default=3.55, help_text='Duração de cada respiração em segundos')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, help_text='Duração real da sessão', null=True)),
                ('planned_duration', models.DurationField(help_text='Duração planejada calculada')),
                ('status', models.CharField(choices=[('in_progress', 'Em Progresso'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='in_progress', max_length=12)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre a sessão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breathing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Respiração',
                'verbose_name_plural': 'Sessões de Respiração',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('max_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('min_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('stress_level_before', models.PositiveIntegerField(blank=True, help_text='Nível de stress antes (1-10)', null=True)),
                ('stress_level_after', models.PositiveIntegerField(blank=True, help_text='Nível de stress depois (1-10)', null=True)),
                ('mood_before', models.CharField(blank=True, max_length=20)),
                ('mood_after', models.CharField(blank=True, max_length=20)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='breathing.breathingsession')),
            ],
            options={
                'verbose_name': 'Estatísticas da Sessão',
                'verbose_name_plural': 'Estatísticas das Sessões',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_breathing_time', models.DurationField(default=datetime.timedelta(0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('blocked', 'Bloqueada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amizade',
                'verbose_name_plural': 'Amizades',
                'unique_together': {('requester', 'addressee')},
            },
        ),
    ]
