# Generated by Django 5.2.6 on 2025-09-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingsession',
            name='hold_times',
            field=models.JSONField(blank=True, default=list, help_text='Lista com tempos de retenção de cada round em segundos'),
        ),
        migrations.AlterField(
            model_name='breathingsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em Progresso'), ('breathing', 'Respiração'), ('holding', 'Retenção'), ('recovery', 'Recuperação'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='in_progress', max_length=12),
        ),
    ]
