source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

gem "rails", "~> 7.1.0"
gem "turbo-rails"
gem "stimulus-rails"
gem "sprockets-rails"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "jbuilder"
gem "redis", "~> 4.0"
gem "bootsnap", ">= 1.4.4", require: false
gem "sassc-rails"
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console", ">= 4.1.0"
  gem "listen", "~> 3.3"
  gem "spring"
end
